name: Terraform Apply

on:
  push:
    branches:
      - main  # Triggers this workflow when changes are pushed to the 'main' branch.

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the code from your repo.
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.9  # Specify your Terraform version here.
          
      - name: Terraform Init
        run: terraform init  # Initialize Terraform.
        
      - name: Terraform Plan
        run: terraform plan  # Check Terraform plan.
        
      - name: Terraform Apply
        run: terraform apply -auto-approve  # Apply the Terraform plan automatically.
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Access the AWS credentials from secrets.
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
